337709: Orphaned Containers Not Cleaned Up by Start Script for DBs
DEFRA/adp-flux-services pull request #87
Opened 2024-04-24 12:25 UTC by santosh-gh

AB#337709

# **What this PR does / why we need it**:
It reduce the number of re-tries for a failed job by setting backoffLimit in each of the Jobs.
The default backoffLimit  is 6, so if a job fails it retries another 6 more times hence create 7 pods
By setting backoffLimit: 2 , it will create a max 3 pods if the job fails.

# **Special notes for your reviewer**
In each of the Job the backoffLimit  is set to 2.
so if the job fails, it will try another 2 times and totally max 3 pods will be created for the failed jobs.
If no backoffLimit is set by default it will create 7 pods for a failed job.

# Testing
*Any relevant testing information and pipeline runs.*
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=536437&view=results

# Checklist (please delete before completing or setting auto-complete)
- [x] Story Work items associated (not Tasks)
- [x] Successful testing run(s) link provided
- [x] Title pattern should be `{work item number}: {title}`
- [x] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests

# **How does this PR make you feel**:

2024-04-24 21:03 UTC, kbabigumira requested changes

2024-04-24 21:03 UTC, kbabigumira commented on services/environments/snd/base/image-update.yaml
> +        branch: sm/337709/OrphanedContainers
Revert back to main branch

2024-04-24 21:03 UTC, kbabigumira commented on services/environments/snd/base/image-update.yaml
> +      branch: sm/337709/OrphanedContainers
revert back to main branch

2024-04-24 21:03 UTC, kbabigumira commented on services/ffc/ffc-ffd/ffc-ffd-backend-poc/pre-deploy/migration/snd/01/migration-patch.yaml
> +          value: ${POSTGRES}
Why was this changed?

2024-04-25 06:24 UTC, santosh-gh commented on services/environments/snd/base/image-update.yaml
> +        branch: sm/337709/OrphanedContainers
Reverted to main

2024-04-25 06:24 UTC, santosh-gh commented on services/ffc/ffc-ffd/ffc-ffd-backend-poc/pre-deploy/migration/snd/01/migration-patch.yaml
> +          value: ${POSTGRES}
Reverted to main

2024-04-25 06:25 UTC, santosh-gh commented on services/environments/snd/base/image-update.yaml
> +      branch: sm/337709/OrphanedContainers
reverted to main branch

2024-04-25 09:50 UTC, kbabigumira approved these changes

2024-04-25 14:48 UTC, ppotturi approved these changes

2024-04-25 14:50 UTC, merged